### ISSUE TITLE
Can you add some instructions ?

### ISSUE THREAD

**Issue by cui2121** [qw3ry/sigclone#1]
Can you add some instructions? 
e.g.
how to use?
What principle is used to detect clones ?
What is the method signature ?

**Comment by qw3ry** [comment]
Hi, have you tried compiling the code and running it with `java -jar sigclone.jar --help`?
I understand that it is hard to understand what is going on without further explanation. I wrote my master thesis on this topic. It is currently not available online, but if you are interested I can email you a copy. If you have more specific questions I am happy to answer.

What is a method signature:
The java method signature consists of return type, method name, and names and types of its parameters

What principle is used to detect clones:
The method signatures are compared to each other. If two signatures are similar, they are considered clones. `sigclone` supports different similarity measures, one of them including an AI trained for natural language processing. The different approaches are described and evaluated in my master thesis.

**Comment by qw3ry** [comment]
Thank you for bringing this up, I've updated the README now.
If you have further questions, please reopen this, or open a new issue.
